#
# ADOBE CONFIDENTIAL
# __________________
#
# Copyright 2020 Adobe Systems Incorporated
# All Rights Reserved.
#
# NOTICE:  All information contained herein is, and remains
# the property of Adobe Systems Incorporated and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to Adobe Systems Incorporated and its
# suppliers and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from Adobe Systems Incorporated.
#
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "98:db:59:8c:95:ec:31:3b:ad:d4:8e:a7:c5:6d:57:8f"
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: |
            echo "Starting Build"
            # circleci user is missing write access to /usr/local/lib/node_modules
            sudo chown -R circleci /usr/local/
            chmod -R u+x+w /usr/local/
            npm install -g @adobe/aio-cli
            npm install
            npm test
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules


workflows:
    version: 2
    build:
        jobs:
        - build:
            context: nui